title: Costyrion
description: AI-Powered Cost Calculation Engine
theme: just-the-docs

url: https://costyrion.io

favicon_ico: /assets/images/favicon.ico
logo: /assets/images/logo.png

aux_links:
  Github Repository: https://github.com/costyrion/costyrion
